apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ports:
    - port: 80
      targetPort: 9898
      protocol: TCP
      name: http
  selector:
    app: podinfo
